- Makefile
- README.md
- app/config.py
- manifest.yml.j2
- migrations/env.py
- paas-failwhale/README.md
- paas-failwhale/manifest.yml
- scripts/run_with_docker.sh
- tests/conftest.py
Before successfully building the Fujitsu "developer-tooling" Docker image from which we can run the containerised development environment, the app name and service references should be updated to reflect the change in ownership from "notifications" to "emergency alerts".
Where the long name/ref is used (notifications-admin), this becomes "emergency-alerts-admin".
The shortened form (notify-admin), as used to name the service instance for example, becomes "eas-admin" (eas -> emergency alerts system).
References to the db also change from notification_api to emergency_alerts_api.
> EAS-476 First pass at changing app refs from notify to eas

- Makefile
- requirements.in
- requirements.txt
- Import the new version of the emergency-alerts-utils package (version 60.0.0-alpha).
- Change package imports to refer to emergency_alerts_utils.
> EAS-476 Change references to utils package to emergency alerts package

- app/celery/broadcast_message_tasks.py
Change alert message headline from "GOV.UK Notify Broadcast" to "GOV.UK Emergency Alert".
> EAS-476 Change alert headline to remove reference to Notify

- app/config.py
To allow the admin, api, celery and database images to run in separate containers:
- A new config class (Decoupled) has been added to the python Flask config file
- The urls assigned in the Decoupled class match the container names assigned by docker-compose (defined in a separate repository)
Note: This configuration will mainly be used as a POC to explore networking and security solutions when running EAS components in isolated containers
> EAS-470 Add Flask config for decoupled docker deployment

- Dockerfile.eas-api
- Dockerfile.eas-celery
- app/status/healthcheck.py
To allow the health check to not only confirm a healthy container, but also that a healthy container is  running the expected image, each service (api, celery & admin) should have a named health check:
- The 'status' route is modified to be specific to the image on which each container is based
- The api container has a health-check endpoint of '/_api_status'
- A celery-specific endpoint has also been added - '/_celery_status' to return the health of the queue when running the celery-beat container. Note: This is a placeholder and currently does not check the function of the celery queue.
> EAS-824 Compose status url from service name

- app/broadcast_message/broadcast_message_schema.py
- app/broadcast_message/rest.py
- tests/app/broadcast_message/test_rest.py
Implemented as part of an accessibility/UX refinement for the alerts admin application, to retain broadcast reference/content state when moving backwards in the new broadcast flow.
While an alert is in a pre-submission state, users should be able to return to these fields and update them. Otherwise, they must rewrite these fields, which is confusing, time-consuming and does not provide a good user experience.
> Update Broadcast Reference/Content While before Submission

- Dockerfile.eas-celery
- app/celery/scheduled_tasks.py
- app/config.py
- scripts/healthcheck.sh
Health check for celery-beat runs as a scheduled job that adds a timestamp to a file.
> EAS-856 Health check scheduled job

- Dockerfile.eas-api
- Dockerfile.eas-celery
- Makefile
- app/__init__.py
- app/config.py
- requirements.in
- requirements.txt
- scripts/docker-build.sh
Further changes to support CI/CD pipeline:
- Utils should be installed from "local" - this folder is baked into the eas-app-base image, so it's existence is guaranteed
- Update notifications-python-client package reference, in anticipation of the Notify email and SMS integration
- Add --no-cache flag to buildx command to ensure the freshest dependencies are used to build the images
- Remove incorrect 'moto' mocking decorator
- Some formatting changes enforced by 'black'
> EAS-447 More changes to prepare for pipeline builds

- Dockerfile.eas-api
- Dockerfile.eas-celery
Build script determines account number at build time - use this environment variable instead of hard-coding the account number.
> EAS-576 Remove hard-coded account numbers from dockerfiles

- app/config.py
When generating the URL that is passed out in the invitation, password-reset and other emails, the ENVIRONMENT should be checked to make sure the "production" domain isn't embedded in the URL.
> EAS-487 Parse the domain in url creation

- app/commands.py
- app/dao/services_dao.py
Remove deprecated default service permissions and create a new service as a training-mode emergency alerts service.
> EAS-994 Clean up "Add New Service" flow for Emergency Alerts

- app/clients/cbc_proxy.py
- app/config.py
- tests/app/clients/test_cbc_proxy.py
Currently, the application attempts to call the proxy lambdas in the same account, because only the name of the function is specified. This accommodates an environment variable to specify which account the Lambdas should be called in. Obviously, it will only be able to trigger Lambdas that the application is authorised to trigger.
> CBC Lambdas can be called specifying account number

- app/clients/cbc_proxy.py
- app/config.py
Celery beat should queue up a period task to be picked up by the govuk-alerts celery worker, to update the health-check timestamp file, used by the AWS govuk-alerts container.
> EAS-1089 Implement govuk-alerts healthcheck celery beat task

- app/config.py
Uses predefined queues as specified in: 
https://github.com/alphagov/emergency-alerts-infra/pull/634
> Use predefined queues with base URL passed in from env variable

- migrations/versions/0389_org_to_emergency_alerts.py
Based on this migration:
https://github.com/alphagov/emergency-alerts-api/commit/aac6b16b3c532d74d788cbad942af6a147a06f4b
The purpose of this to update the organisation name from Broadcast Service (environment_name) to Emergency Alerts due to the nature of Emergency Alerts, we don't use multiple organisations, just multiple services.
> Add migration to update organisation name

- app/dao/services_dao.py
- app/platform_admin/rest.py
- tests/app/dao/test_services_dao.py
- tests/app/service/test_rest.py
- tests/app/test_commands.py
- tests/app/v2/broadcast/test_post_broadcast.py
Services default to having broadcast permissions, to resolve the "Page not found" issue for created services - all services in Emergency Alerts will require broadcast permissions.
It also adds an API endpoint for searching for objects by UUID, similar to this feature in Notify: https://github.com/alphagov/notifications-api/commit/5ff4d2730b45427c64d628bac319c57e64b9c1fc
Relates to: https://github.com/alphagov/emergency-alerts-admin/pull/64
> Default services to allow broadcast

- app/clients/cbc_proxy.py
EE don't have a failover lambda in their staging environment
- This PR defines a check to ensure the lambda isn't invoked, reducing errors
> Block invocation of secondary lambda in EE's staging environment

- app/celery/scheduled_tasks.py
- app/config.py
- tests/app/celery/test_scheduled_tasks.py
Add a celery-beat scheduled task to periodically validate the accounts used by the functional tests.
> EAS-1515 Scheduled job for functional-test account validation

- Makefile
- app/broadcast_message/rest.py
- app/commands.py
- app/config.py
- app/dao/broadcast_message_dao.py
- docker-compose-tests.yml
- tests/app/broadcast_message/test_rest.py
- tests/app/dao/test_broadcast_message_dao.py
- tests/app/db.py
This PR adds a method for purging old alerts from the database:
- At this time, this is only intended for use in the preview environment, due to the large number of alerts generated daily by the functional tests
- The new database method has supporting unit tests, which verify the purging of BroadcastMessage, BroadcastEvent, BroadcastProviderMessage and BroadcastProviderMessageNumber items
- The new method can be reached via an api call or via a command
- The purge method requires a service ID as well as a value specifying the minimum age of messages to be purged
- A 'dry-run' parameter can be used in the terminal to display the items that will be purged, without removing them from the database.
> EAS-1865 Purging Test Alerts on Preview

- Makefile
- app/celery/broadcast_message_tasks.py
- app/celery/scheduled_tasks.py
- app/config.py
This PR adds the account used by the "platform-admin-flow" integration (smoke) tests to the periodic user refresh job.
This will prevent the test failing due to the email validity check (The one which throws up the splash screen that says "For security, we need to check if you still have access to your email address.").
> EAS-1887 Smoke test partitioning

- app/config.py
Need to add a db connection string override for local running (i.e. true local running, not in a container)
> EAS-2000 Fix for local running

- app/service/rest.py
Fix TypeError by concatenating a list of IDs, rather than a dictionary.
> EAS-2027 Modify rest return value

- app/dao/templates_dao.py
The db query has been simplified to target only the templates associated with the target service.
Purge method has been verified by authoring templates in the 'functional test service' and 'cabinet office - severe' service, running the functional tests and then confirming that the cabinet office templates are still usable.
> EAS-2084 Fix template purge on Pytest setup

- app/v2/broadcast/post_broadcast.py
- tests/app/v2/broadcast/test_post_broadcast.py
The "is the api alive" question can be answered by querying the endpoint v2/broadcast with the "OPTIONS" method.
This endpoint handler returns an empty response, with a header showing which methods are allowed on the url, i.e. "OPTIONS, POST".
> EAS-2243 Add OPTIONS method

- app/celery/broadcast_message_tasks.py
With "retry_jitter: True" the retry delay may be zero - empirical observation suggests that the application (celery?) does not handle this reliably and some retries can be lost.
> EAS-2322 Remove randomness from retry backoff

- app/__init__.py
- app/config.py
- app/reports/rest.py
- tests/app/reports/test_rest.py
(Note that the tests fail here currently because they rely on a change being made to Utils. There is a corresponding PR for this here: https://github.com/alphagov/emergency-alerts-utils/pull/86)
> Implement reporting endpoints

- app/celery/broadcast_message_tasks.py
- tests/app/celery/test_broadcast_message_tasks.py
Pass broadcast-event-id to Celery task so that the logs can show which alert triggered the re-render of HTML and upload to S3
> EAS-1055 Pass broadcast-event-id to Celery task

- .codepipeline/buildspec-api-build.yml
- .codepipeline/buildspec-celery-build.yml
- .codepipeline/buildspec-celery-deploy.yml
In combination with https://github.com/alphagov/emergency-alerts-infra/pull/1263 this lets developers provide a feature branch to construct their builds from.
The idea is that MANUAL_PIPELINE_BRANCH will only be present if configured, so existing workflows should remain as they are, both for the legacy development technique and later environments.
> EAS-2592: API: Use MANUAL_PIPELINE_BRANCH if present 

- app/models.py
By avoiding the deprecated `utcnow` I introduced a rather embarassing bug - the column default was evaluated when the server started and thus meant `created_at` would always be a bit meaningless.
The rest of this file _does_ use `utcnow` but I thought it's best not to clutter too much by changing it throughout.
> EAS-2569: API: Fix AdminAction created_by being the server's start time

- app/dao/users_dao.py
- app/service/rest.py
This PR adds a function to the purge route that the functional tests call to clean up the users that have been created with each. The function deletes all of the permissions associated with the user that is to be deleted, to avoid the foreign key constraint error.
> Adds deletion of user permissions to purge route for functional tests

- app/admin_action/rest.py
- app/dao/admin_action_dao.py
As title, for upcoming functional testing it'll be nice to wipe out all of admin actions it implicitly creates as it does for other entities (services, etc).
> EAS-2569: API: Add endpoint to purge test admin actions

- .codepipeline/buildspec-api-build.yml
- .codepipeline/buildspec-celery-build.yml
This PR removes the tag checkout in the `buildspec.yml`. It has been agreed that this is a historical artefact, from a time where CodePipeline was not capable of sourcing a particular commit hash, so there was no way to actually run a pipeline with a non-HEAD commit - or even a commit that wasn't latest@main, because generally it's inadvisable to change the source branch of the pipeline, as that's a permanent configuration difference that does class as a form of infra drift.
Nowadays (and as of [November 2023](https://aws.amazon.com/about-aws/whats-new/2023/11/aws-codepipeline-pipeline-execution-source-revision-overrides/)) you can use the `source revision override` feature to run CodePipeline on an arbitrary commit hash. Given our main concern was facilitating quick rollbacks or …
> Remove buildspec tag checkout

- app/dao/broadcast_service_dao.py
- app/models.py
- app/schemas.py
- migrations/versions/0413_remove_old_service_code.py
- tests/app/service/test_rest.py
Remove db objects and ORM code related to the old way of linking services to target MNOs.
> EAS-2626 Remove deprecated code and fix tests

- .github/workflows/on-pr-into-main.yml
This PR adds the ability for PR checks to be run on pull requests to the main branch even when they are in a draft state. Currently, they only run when the PR is in a "Ready for review" state, which isn't very helpful in instances where you want an easy way of checking the build status of your work on the branch itself, without indicating to other people that you would like your PR to be reviewed.
Corresponding PRs will be made for Utils, API, Admin, and gov.uk/alerts
> Add PR checks even when a PR is in a drafted state

- requirements.in
- requirements.txt
https://github.com/alphagov/emergency-alerts-utils/pull/100 brings in its own requirement on `lxml`, itself brought over from the CBC proxy. This is on 5.2.2, but API specifies the older 4.9.1 which causes a dependency conflict.
I just bump the version here. It seems `lxml` is only used to validate CAP XML in the post schema, and related tests are still passing.
> EAS-2637: API: Bump lxml from 4.9.1 to 5.2.2

- Dockerfile.eas-api
`docker build` fails without this now, due to https://www.postgresql.org/message-id/aItWGvIAWFEsLqds%40msg.df7cb.de
This is a temporary fix - we'll be replatforming base in due course. I've tested this in preview.
> Move to Postgres archive apt repo to unblock builds

- app/broadcast_message/utils.py
Removing the link to a deprecated runbook. Most of its contents no longer apply to the system as it is today.
> Remove deprecated runbook link

- app/broadcast_message/rest.py
- app/dao/templates_dao.py
- app/models.py
- app/template/rest.py
- app/template/template_schemas.py
- app/v2/template/template_schemas.py
- migrations/versions/0419_add_area_col.py
- tests/app/broadcast_message/test_rest.py
- tests/app/conftest.py
- tests/app/dao/test_templates_dao.py
- tests/app/db.py
- tests/app/template/test_rest.py
- tests/app/v2/template/test_template_schemas.py
- tests/app/v2/templates/test_templates_schemas.py
This PR adds the migration version that adds the areas column to both `templates` and `template_history`, as well as renaming the "name" column to "reference".
> Adds migration version for adding area column for Templates

- docker-compose-tests.yml
- migrations/versions/0421_add_postgis_extension.py
- tests/app/test_db.py
This PR consists of the following:
- Adds a migration version for adding the PostGIS extension to the database
- Adds tests asserting that extension has been added and the functions, that it provides, are present
- Updates image for database test container, to use image that supports PostGIS extension
> EAS-2074 Add PostGIS extension

- .github/dependabot.yml
See https://github.com/alphagov/emergency-alerts-api/network/updates/1114953606 / #250
Quite why Dependabot fails the entire run if can't resolve one dependency I've no idea, but there we are.
> EAS-2767: API: Update Dependabot to ignore the local utils dep
