alphagov/emergency-alerts-api

Dockerfile.eas-api, Dockerfile.eas-celery, scripts/docker-build.sh, scripts/start-api.sh, scripts/start-celery.sh
For the images to be built by the CI pipeline, the following changes have been made:
- The dockerfile starts from a base layer built in the Utils repo that includes Linux tools and emergency-alerts-utils codebase
- The dockerfile is refactored to removed the redundant Utils clone & build step
- The API and Celery start scripts have been localised to this repo for inclusion in the build step
=> EAS-446 Refactored dockerfiles & scripts for CI/CD pipeline

Dockerfile.eas-api, Dockerfile.eas-celery, Makefile, app/__init__.py, app/broadcast_message/rest.py, app/celery/broadcast_message_tasks.py, app/clients/cbc_proxy.py, app/config.py, app/status/healthcheck.py, docker-compose-tests.yml, postgres/init-user-db.sh, postgres/pg_hba.conf, postgres/postgresql.conf, scripts/docker-build.sh, tests/app/celery/test_broadcast_message_tasks.py, tests/app/clients/test_cbc_proxy.py, tests/app/conftest.py, tests/app/dao/test_services_dao.py, tests/app/performance_dashboard/test_rest.py, tests/app/status/test_status.py
As another step toward self-contained Fargate deployed microservices, the following changes have been made to the Emergency Alerts API repo:
- Consolidate RUN commands in API and Celery dockerfiles to reduce layer count
- Upon emergency alert broadcast, replace celery task defined in govuk-alerts repo with code to post a message to an SNS topic
- Mocking via 'moto' library has been added where necessary to fix unit tests
- A docker compose file has been added to allow the tests to run with a containerized instance of postgres
- The tests have been updated to work with postgres 14 (up from version 11)
=> ESA-447 Containerized build image

Dockerfile.eas-api, Dockerfile.eas-celery, scripts/docker-build.sh, scripts/start-api.sh
Pass account number as argument to dockerfile
=> EAS-576 Pass account number as argument

app/config.py, scripts/start-api.sh
Startup script for API checks the DB migration version:
- If the database is up to date, the message 'DB is up to date' is echoed out
- If the database is behind the head migration point, 'flask db upgrade' is invoked
- The master credentials are cleared from environment variables so subsequent db access is done via SSL cert
=> EAS-880 Add upgrade step to startup script

app/config.py, scripts/start-api.sh
Regardless of which code branch executes in the startup script, the master credentials should be cleared before exiting the function.
=> EAS-880 Clear master credentials

Dockerfile.eas-api, Dockerfile.eas-celery
Changing ownership of the utils directory from root to easuser
=> eas user ownership of utils directory

Makefile, README.md, app/__init__.py, app/clients/notify_client.py, app/config.py, app/user/rest.py
- Add defaults for config variables that won't be supplied by the environment
- Add instructions for setting up the environment.sh file
- Add special cases for when the app is running locally
=> EAS-1034 Changes for local running

Dockerfile.eas-api, Dockerfile.eas-celery
Upgrading python version to 3.9.16 in line with security requirements
=> upgrading python version

app/__init__.py, app/user/rest.py, tests/app/test_config.py
Minor changes to fix formatting errors raised by 'black' and also to fix unit tests that are dependent on config value that recently changed.
=> EAS-1070 Fix formatting and unit tests

migrations/versions/0389_org_to_emergency_alerts.py, migrations/versions/0390_remove_default_service.py
Fix the linting errors (formatting/layout) introduced with recent changes
=> EAS-1211 Fix linting errors

.github/workflows/on-pr-into-main.yml, .github/workflows/pr-checks.yml, docker-compose-tests.yml, scripts/docker-build.sh
Add github action definition to run basic checks when a PR is raised
=> EAS-1202 Add pr checks

.github/workflows/on-pr-into-main.yml
Add apt-get update to PR into main to make sure package vers are up to date
=> Add apt-get update to PR into main

.codepipeline/buildspec-api-build.yml, .codepipeline/buildspec-celery-build.yml, .codepipeline/buildspec-celery-deploy.yml
Adding tagging to be pushed with the image in order to have the pipeline execution ID and commit ID included in the image
=> adding proper tagging

app/__init__.py, app/dao/users_dao.py, app/models.py, app/user/rest.py, app/verify/rest.py
Add new endpoint to return the latest verify code, filtered by user id.
=> EAS-1243 Endpoint to return latest verify code for a user

app/clients/cbc_proxy.py
This adds a line to log success, along with the existing logging for error states
=> EAS-89 Log lambda success

app/broadcast_message/rest.py, app/dao/broadcast_message_dao.py
The functional tests need a way to retrieve the individual provider broadcast message IDs given the parent broadcast message ID.
=> EAS-1549 Add endpoint to retrieve provider message IDs

app/broadcast_message/rest.py, app/dao/broadcast_message_dao.py, tests/app/broadcast_message/test_rest.py
Improve name of endpoint method and add unit test.
=> EAS-1549 CBC tests endpoint

.github/workflows/on-pr-into-main.yml, app/config.py
Set secret that allows intra-VPC comms between api and admin instances from environment variables
=> EAS-1808 Set internal secret from env var

app/celery/scheduled_tasks.py, tests/app/celery/test_scheduled_tasks.py
Changes have been made to the accounts used by the functional tests. This PR modifies the periodic update task to match.
=> EAS-1972 Update emails to match those used by functional tests

app/config.py, requirements.in, requirements.txt
Remove unused dependencies that conflict with the Pyyaml version coming in from Utils
=> EAS-2000 Bump pyyaml version and remove unused dependencies

README.md
Linked to confluence pages recently created to consolidate the local development environment setup instructions.
=> EAS 1857 Updates README

requirements.in, requirements.txt, tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py, tests/app/letters/test_letter_utils.py
Upgrade Flask to pull in the latest version of Werkzeug (required to be upgraded to latest version https://github.com/alphagov/emergency-alerts-api/security/dependabot/2)
=> EAS-2028 Apply version upgrades

app/broadcast_message/rest.py, app/commands.py, app/dao/services_dao.py, app/dao/template_folder_dao.py, app/dao/templates_dao.py, app/service/rest.py, app/template/rest.py, app/template_folder/rest.py, requirements.in, requirements.txt, tests/app/broadcast_message/test_rest.py, tests/app/dao/test_services_dao.py, tests/app/dao/test_template_folder_dao.py, tests/app/dao/test_templates_dao.py, tests/app/db.py, tests/app/template/test_rest.py
Added endpoints for purging functional test artefacts from the preview environment.
=> EAS-2012 Clean Up DB on Functional Test Run

app/commands.py, app/dao/invited_user_dao.py, app/models.py, app/service/rest.py, app/service_invite/rest.py, app/user/rest.py, tests/app/dao/test_invited_user_dao.py
API changes to support functional tests, implemented in PR https://github.com/alphagov/emergency-alerts-functional-tests/pull/68
=> EAS-2021 API changes to support Functional Tests

requirements.in, requirements.txt
Fix the following High severity vulnerability:
https://github.com/alphagov/emergency-alerts-api/security/dependabot/25
=> EAS-2050 Security patches

app/service_invite/rest.py, app/user/rest.py, app/utils.py
Add logs for user invitations (creation of InvitedUser record) and registration (creation of active User record).
=> EAS-2218 Log user invitations and registrations

app/user/rest.py, app/utils.py
For admin accounts only:
- Log successful authentication events
- Log failed auth events, including failed_login_count
=> EAS-2214 Log auth activity for platform admins

app/service/rest.py
Remove the users created by the functional tests (preview only)
=> EAS-2235 Purge test users

app/failed_logins/rest.py, app/user/rest.py, tests/app/user/test_rest.py
- Ensure the check for existence of a user is not logged as a failed login when in the new user registration flow
=> EAS-2366 Prevent throttling during registration

migrations/versions/0404_drop_constraints.py
These records will be removed in a subsequent PR
=> EAS-2447 Remove ops that violate constraints

app/clients/notify_client.py
Enhance logging around calls to the Notify service (used to send sms and email messages).
=> EAS-2536 add logging to notify api calls

app/config.py, app/dao/users_dao.py, app/user/rest.py, app/utils.py, tests/app/user/test_rest.py, tests/app/user/test_rest_verify.py
This PR includes:
- Addition of `get_user_by_email_or_none` DAO method that returns either User or None, depending on whether User exists in table with specified email address
- Addition of `fetch_user_by_email_or_none` route using `get_user_by_email_or_none` DAO method
- Adjustment to `calculate_delay_period` to implement the agreed delay timings
- Adjustments to existing tests
=> EAS-2474 Reduce throttling sensitivity

app/broadcast_message/utils.py, app/celery/broadcast_message_tasks.py, app/models.py
> **Requires https://github.com/alphagov/emergency-alerts-utils/pull/102**
These constants and util method have been moved to the attached utils PR.
=> EAS-2602 + EAS-2603: API: Use new constants
